api_platform:
    enable_fos_user: true
    formats:
        jsonld:  ['application/ld+json']
        json:    ['application/json']
        html:    ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    oauth:
          # To enable or disable oauth.
          enabled: false

framework:
    form: { enabled: true }
