nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: false
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        max_age: 3600
    paths:
        '^/': ~
