nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: false
        allow_origin: ['*']
        allow_methods: ['POST']
        allow_headers: ['Content-Type', 'Accept']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
