security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_CLIENT: ROLE_USER
    ROLE_COMMERCIAL: ROLE_USER
    ROLE_MARKET_LEADER: ROLE_USER
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN]

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  firewalls:
    main:
      pattern:   ^/
      provider: fos_userbundle
      stateless: true
      anonymous: true
      json_login:
        check_path: /login_check
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      logout:
        path:   fos_user_security_logout
        target: /
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: true
      provider: fos_userbundle
      stateless: true
      anonymous: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
  - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/login, role: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
  - { path: ^/logout, role: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
  - { path: ^/resetting, role: [ IS_AUTHENTICATED_ANONYMOUSLY ] }

  - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

  - { path: ^/api/users, roles: [ ROLE_ADMIN ] }

  - { path: ^/api/articles, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
  - { path: ^/api/paniers$, roles: [ ROLE_USER ] }
  - { path: ^/api/categories, role: IS_AUTHENTICATED_ANONYMOUSLY }

  - { path: ^/api/ws/clients, roles: [ ROLE_COMMERCIAL, ROLE_MARKET_LEADER ] }
  - { path: ^/api/ws/contacts, roles: [ ROLE_COMMERCIAL, ROLE_MARKET_LEADER ] }

  - { path: ^/api/ws/devis$, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
  - { path: ^/api/ws/factures$, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
  - { path: ^/api/ws/bonslivraison$, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
  - { path: ^/api/ws/commandes$, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
  - { path: ^/api/ws/factures-en-attentes$, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

  - { path: ^/api/ws/editions, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

  - { path: ^/api/ws/libelles, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

  - { path: ^/api/ws/depots, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

  - { path: ^/api/ws/statistiques, roles: [ ROLE_CLIENT, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }