security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_COMMERCIAL: ROLE_USER
        ROLE_MARKET_LEADER: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path: /login_check
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:   ^/
            provider: fos_userbundle
            stateless: true
            anonymous: true
            logout:
                path:   fos_user_security_logout
                target: /
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: true
            provider: fos_userbundle
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
        - { path: ^/logout$, role: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

        - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api/users, roles: [ ROLE_ADMIN ] }

        - { path: ^/api/articles, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY ] }

        - { path: ^/api/devis, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
        - { path: ^/api/factures, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
        - { path: ^/api/bonslivraison, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
        - { path: ^/api/commandes, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
        - { path: ^/api/factures-en-attentes, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

        - { path: ^/api/editions$, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

        - { path: ^/api/libelles, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }

        - { path: ^/api/depots, roles: [ ROLE_USER, ROLE_COMMERCIAL, ROLE_MARKET_LEADER, ROLE_ADMIN ] }
