# Project language
language: php

# Allows use container-based infrastructure
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2
#    - php: hhvm
#  allow_failures:
#    - php: hhvm

# Define an environment variable
env:
    - SYMFONY_VERSION="4.2" DB=mysql

# Update composer
before_install:
    - sudo mysql_upgrade
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('passtest') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo service mysql restart
    - composer self-update
    - cp .env.test.dist .env



# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load -n

before_script:
  - rm -Rf /var/cache/prod
  - rm -Rf /var/cache/dev

# Run script
script:
  - bin/behat
  - bin/phpunit

# After a build, send email notification with the build results
notifications:
  email: n.cartier@dfc2.biz, b.grisot@dfc2.biz
