# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.2
#    - php: hhvm
#  allow_failures:
#    - php: hhvm

# Define an environment variable
env:
    - SYMFONY_VERSION="4.1.*" DB=mysql

# Update composer
before-install:
    - composer self-update
    - cp .env.test.dist .env
    - cat .env



# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

# Run script
script:
  - behat

# After a build, send email notification with the build results
notifications:
  email: n.cartier@dfc2.biz
