settings:
  index:
    # single node, no sharding
    number_of_shards: 1
    number_of_replicas: 0
mappings:
  article:
    dynamic: false # disable dynamic mapping
    properties:
      PlusAD: &fr_text
        type: text
        analyzer: french
      DescriCatalogAD: *fr_text
      DescriWebAD: *fr_text
      slug: *fr_text
      DesiAD: *fr_text
      DesiPrincAD: *fr_text
      # ---
      # champs utilent mais pas de recherche dedans
      # ---
#      IdArtEvoAD: &notanalyze_int
#        type: integer
#        index: not_analyzed
#      MediasAD: &notanalyze_text
#        type: text
#        index: not_analyzed
#      OrdreAD: *notanalyze_int
#      NumDecliAD: *notanalyze_int
#      FlgAncAD: *notanalyze_int
#      FlgCatalogAD: &notanalyze_bool
#        type: boolean
#        index: not_analyzed
#      FlgPrincAD: *notanalyze_bool
#      FlgDestockAD: *notanalyze_bool
#      FlgHorsMarqueAD: *notanalyze_bool
#      FlgNouvAD: *notanalyze_bool
#      FlgPromoAD: *notanalyze_bool
#      FlgVisibleAD: *notanalyze_bool
#      FlgEclBleuAD: *notanalyze_bool
#      FlgEclRoseAD: *notanalyze_bool
#      FlgEclVertAD: *notanalyze_bool
#      FlgEclOrangeAD: *notanalyze_bool
#      IdFourAD: *notanalyze_int
#      DateCreAD: &notanalyze_date
#        type: date
#        index: not_analyzed
#      DateModAD: *notanalyze_date
#      UCreAD: *notanalyze_text
#      UModAD: *notanalyze_text
#      # ---
#      # hydraté par les web services
#      # ---
#      IdAD: *notanalyze_int
#      IdArt: *notanalyze_int
#      IdSoc: *notanalyze_int
#      IdDep: *notanalyze_int
#      IdIC: *notanalyze_int
#      NoAD: *notanalyze_int
#      CodAD: *notanalyze_text
#      #DesiAutoAD: *notanalyze_text
#      ValNivAD: *notanalyze_text
#      StkReelAD: &notanalyze_float
#        type: float
#        index: not_analyzed
#      StkResAD: *notanalyze_float
#      StkCmdeAD: *notanalyze_float
#      CodGesStkAD: *notanalyze_text
#      EtatStockAD: *notanalyze_text
#      StockDisponible: *notanalyze_float
#      StockDisponibleSoc: *notanalyze_float
#      StockPratique: *notanalyze_float
#      StkReelPlat1: *notanalyze_float
#      QteCIDSsCFAD: *notanalyze_int
#      UVteArt: *notanalyze_text
#      UStoArt: *notanalyze_text
#      CvStoVteAD: *notanalyze_text
#      TypCvStoVteAD: *notanalyze_text
#      NbUStoCondVteAD: *notanalyze_float
#      PoidsUVteArt: *notanalyze_float
#      NbUVteUCondVte: *notanalyze_int
#      #PrixPubUCondVte: *notanalyze_float
#      PrixNetUCondVte: *notanalyze_float
#      NbUStoUVte: *notanalyze_int
#      NbUVteUSto: *notanalyze_int
#      NbrDecArt: *notanalyze_int
#      LongAD: *notanalyze_int
#      LargAD: *notanalyze_int
#      EpaisAD: *notanalyze_int
#      CondVteAD: *notanalyze_text
#      FlgDecondAD: *notanalyze_bool
#      Desi2Art: *notanalyze_text
#      IdFour: *notanalyze_int
#      NomDep: *notanalyze_text
#      CodSuspAD: *notanalyze_int
#      MultimediaArt: *notanalyze_text
#      ComTechAD: *notanalyze_text
#      #DocLie: *notanalyze_text
#      GenCodAD: *notanalyze_text
#      CodEcoTaxeAD: *notanalyze_text
#      MtEcoTaxe: *notanalyze_float
#      ValEcoTaxe: *notanalyze_text
#      IdDepPlat: *notanalyze_int
#      IdADF: *notanalyze_int
#      CodADF: *notanalyze_int
#      GenCod1ADF: *notanalyze_text
#      GenCod2ADF: *notanalyze_text
#      CodCatAD: *notanalyze_text
#      PrixNet: *notanalyze_float
#      PrixPubCli: *notanalyze_float
#      PrixPubAD: *notanalyze_float
#      TypeTarif: *notanalyze_text
#      PrixRevConvAD: *notanalyze_float
#      PrixRevReelAD: *notanalyze_float
#      CoefPRRAD: *notanalyze_float
#      CoefPRCAD: *notanalyze_float
#      MargeReelleAD: *notanalyze_float
#      MargeConvAD: *notanalyze_float
#      Stocks: *notanalyze_int