settings:
   index:
      # single node, no sharding
      number_of_shards: 1
      number_of_replicas: 0
mappings:
    article:
      dynamic: false # disable dynamic mapping
         properties:
            NoAD:
               type: integer
            DesiAD: &fr_text
               type: text
               analyzer: french
            DesiPrincAD: *fr_text
            CodAD: *fr_text
            DescriCatalogAD: *fr_text
            DescriWebAD: *fr_text
            PlusAD: *fr_text
            slug: *fr_text
            # ---
            # champs utilent mais pas de recherche dedans
            # ---
            IdArtEvoAD: &notanalyze_int
               type: integer
               index: false
            MediasAD: &notanalyze_text
               type: text
               index: false
            OrdreAD: *notanalyze_int
            NumDecliAD: *notanalyze_int
            FlgAncAD: &notanalyze_bool
               type: boolean
               index: false
            FlgCatalogAD: *notanalyze_bool
            FlgPrincAD: *notanalyze_bool
            FlgDestockAD: *notanalyze_bool
            FlgHorsMarqueAD: *notanalyze_bool
            FlgNouvAD: *notanalyze_bool
            FlgPromoAD: *notanalyze_bool
            FlgVisibleAD: *notanalyze_bool
            FlgEclBleuAD: *notanalyze_bool
            FlgEclRoseAD: *notanalyze_bool
            FlgEclVertAD: *notanalyze_bool
            FlgEclOrangeAD: *notanalyze_bool
            IdFourAD: *notanalyze_int
            # ---
            # hydraté par les web services
            # ---
            DesiAutoAD: *notanalyze_text
            UVteArt: *notanalyze_text
            UStoArt: *notanalyze_text
            PrixPubUCondVte: &notanalyze_float
               type: float
               index: false
            PrixNetUCondVte: *notanalyze_float
            LongAD: *notanalyze_int
            LargAD: *notanalyze_int
            EpaisAD: *notanalyze_int
            CondVteAD: *notanalyze_text
            FlgDecondAD: *notanalyze_bool
            Desi2Art: *notanalyze_text
            IdFour: *notanalyze_int
            NomDep: *notanalyze_text
            CodSuspAD: *notanalyze_int
            GenCodAD: *notanalyze_text
            CodADF: *notanalyze_text
            GenCod1ADF: *notanalyze_text
            GenCod2ADF: *notanalyze_text
            PrixNet: *notanalyze_float
            PrixPubCli: *notanalyze_float
            PrixPubAD: *notanalyze_float
            PrixRevConvAD: *notanalyze_float
            CoefPRCAD: *notanalyze_float
            MargeConvAD: *notanalyze_float