#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

app.swagger_ui:
    path: /api/doc
    methods: [GET, POST, DELETE, PUT]
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
