# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    dfc2.api.admin_user: '%env(WSADMIN_USER)%'
    dfc2.api.admin_password: '%env(WSADMIN_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true        # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'


    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }


    App\Services\WsManager:
        class: App\Services\WsManager
        autowire: true
        public: true
        arguments:
          $wsAdminUser: '%dfc2.api.admin_user%'
          $wsAdminPassword: '%dfc2.api.admin_password%'

    dfc2.api.manager:
        alias: App\Services\WsManager
        public: true

    dfc2.user.service:
        public: true
        autowire: true
        class: App\Services\UserService
        arguments: [ '@security.token_storage', '@dfc2.api.manager' ]

    App\Services\Filter\WsFilter:
        public: true
        autowire: false

    App\Services\Json\ResponseDecode:
        public: true
        autowire: false

    App\Services\Objets\:
        resource: '../src/Services/Objets'
        public: true
        autowire: false

    App\Utils\:
      resource: '../src/Utils'
      public: true
      autowire: false


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        arguments: [ '@dfc2.api.manager', '@dfc2.user.service' ]

    App\Repository\:
        resource: '../src/Repository'
        autowire: true


    App\EventSubscriber\TransformResponseSubscriber:
            tags:
                - { name: kernel.view }
            arguments: [ '@dfc2.api.manager', '@dfc2.user.service' ]


    # lexik_jwt_authentication EVENTS
    dfc2.api.event.authentication_success_listener:
            autowire: true
            class: App\EventListener\AuthenticationSuccessListener
            tags:
                - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
            arguments: [ '@dfc2.api.manager', '@dfc2.user.service' ]

    dfc2.api.event.authentication_failure_listener:
            autowire: true
            class: App\EventListener\AuthenticationFailureListener
            tags:
                - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    dfc2.api.event.jwt_invalid_listener:
            autowire: true
            class: App\EventListener\AuthenticationTokenInvalidListener
            tags:
                - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }

    dfc2.api.event.jwt_notfound_listener:
            autowire: true
            class: App\EventListener\AuthenticationTokenNotFoundListener
            tags:
                - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }

    dfc2.api.event.jwt_expired_listener:
            autowire: true
            class: App\EventListener\AuthenticationTokenExpiredListener
            tags:
                - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }
